version: '3'
services:
  edge_device_1:
    image: muto_edge_device
    container_name: edge_device_1
    networks:
      - composer_net
  edge_device_2:
    image: muto_edge_device
    container_name: edge_device_2
    networks:
      - composer_net

networks:
  composer_net:
    driver: bridge
